name: 'Continuous Delivery'

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: projects/282015016889/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: github-actions@project-56d8b425-e46f-472e-a79.iam.gserviceaccount.com

      - name: Configure Docker for GCR
        run: gcloud auth configure-docker --quiet

      - name: Build and push Docker image
        run: |
          docker buildx build --platform linux/amd64 \
            -t gcr.io/project-56d8b425-e46f-472e-a79/challenge-mle \
            --push .

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy challenge-mle \
            --image gcr.io/project-56d8b425-e46f-472e-a79/challenge-mle \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --port 8080
